<?php

namespace BookmarkBundle\Repository;

/**
 * EmployersBookmarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployersBookmarkRepository extends \Doctrine\ORM\EntityRepository
{
}
