<?php

namespace BookmarkBundle\Repository;

/**
 * FreelancersBookmarkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FreelancersBookmarkRepository extends \Doctrine\ORM\EntityRepository
{
}
