bids:
    path:     /bids
    defaults: { _controller: BidBundle:Bid:bids }

bidders:
    path:     /bidders/{id}
    defaults: { _controller: BidBundle:Bid:manageBidders }

place_bid:
    path:     /place/{deliveryTime?}/{hourlyRate?}
    defaults: { _controller: pl }


cancel_bid:
    path:     /cancel
    defaults: { _controller: BidBundle:Bid:canelBid }


edit_bid:
    path:     /edit
    defaults: { _controller: BidBundle:Bid:editBid }

accept_offer:
    path:     /accept/{id}/{projectid}
    defaults: { _controller: BidBundle:Bid:acceptBid }