fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
login:
    path:     /login
    defaults: { _controller: UserBundle:Security:login }

profile:
    path:     /profile/edit
    defaults: { _controller: UserBundle:Profile:edit }





