<?php

namespace ProjectBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByString($str)
    {
        try {
            $conn = $this->getEntityManager()->getConnection();

            $sql = "SELECT projectName, projectLocation, projectDescription, minBudget, maxBudget from Project WHERE projectDescription like '%$str%' GROUP by projectName";
            $stmt = $conn->prepare($sql);
            $stmt->execute();
            return $stmt->fetchAll();
        } catch (DBALException $e) {
        }


    }

    public function findParameters($loc, $cat, $sk, $sort) {
        $sql = '';
        if ($cat != 'any') {
            $sql=$sql." and l.idCategory=".$cat." ";
        }
        if ($sk != 'any') {
            $sql=$sql." and l.idSkill=".$sk." ";
        }
        if($sort != 'any') {
            $sql=$sql . " order by l.".$sort.' desc';
        }
        $query=$this->getEntityManager()
            ->createQuery("select l from ProjectBundle:Project l where l.projectLocation like :parameter ".$sql)
            ->setParameter('parameter','%'.$loc.'%');
        return $query->getResult();
    }




}
