api_bids:
    path:     /all
    defaults: { _controller: BidApiBundle:BidApi:allBids }

api_place_bid:
    path:     /place/{deliveryTime}/{hourlyRate}
    defaults: { _controller: BidApiBundle:BidApi:placeBid }

api_find_bid:
    path:     /find/{id}
    defaults: { _controller: BidApiBundle:BidApi:findBid }



