<?php

namespace ReviewBundle\Repository;

/**
 * ReviewEmpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewEmpRepository extends \Doctrine\ORM\EntityRepository
{
}
