create_task:
    path:     /create
    defaults: { _controller: ProjectBundle:Project:createProject }


manage_projects:
    path:     /manage
    defaults: { _controller: ProjectBundle:Project:manage_projects }



delete_project:
    path:     /delete/{id}
    defaults: { _controller: ProjectBundle:Project:delete_manage_projects }

update_project:
    path:     /update/{id}
    defaults: { _controller: ProjectBundle:Project:update_manage_projects }


project:
    path:     /project/{id}
    defaults: { _controller: ProjectBundle:Project:singleProject }

listprojects:
    path:     /projects
    defaults: { _controller: ProjectBundle:Project:projects }

searchParameters:
    path:     /searchParameters
    defaults: { _controller: ProjectBundle:Project:searchParameters }

mail:
    path:     /mail/{address}
    defaults: { _controller: ProjectBundle:Project:mail }





bookmark_project:
    path:     /book/{id}
    defaults: { _controller: ProjectBundle:Project:bookMark }



